// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createClick = `-- name: CreateClick :one
INSERT INTO url_clicks (url_id, ip_address, user_agent, referer, country, city, device_type, browser, os, is_bot)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, url_id, ip_address, user_agent, referer, country, city, device_type, browser, os, is_bot, clicked_at
`

type CreateClickParams struct {
	UrlID      uuid.UUID
	IpAddress  pqtype.Inet
	UserAgent  sql.NullString
	Referer    sql.NullString
	Country    sql.NullString
	City       sql.NullString
	DeviceType sql.NullString
	Browser    sql.NullString
	Os         sql.NullString
	IsBot      sql.NullBool
}

func (q *Queries) CreateClick(ctx context.Context, arg CreateClickParams) (UrlClick, error) {
	row := q.db.QueryRowContext(ctx, createClick,
		arg.UrlID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Referer,
		arg.Country,
		arg.City,
		arg.DeviceType,
		arg.Browser,
		arg.Os,
		arg.IsBot,
	)
	var i UrlClick
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.IpAddress,
		&i.UserAgent,
		&i.Referer,
		&i.Country,
		&i.City,
		&i.DeviceType,
		&i.Browser,
		&i.Os,
		&i.IsBot,
		&i.ClickedAt,
	)
	return i, err
}

const getURLAnalytics = `-- name: GetURLAnalytics :many
SELECT id, url_id, ip_address, user_agent, referer, country, city, device_type, browser, os, is_bot, clicked_at FROM url_clicks WHERE url_id = $1
ORDER BY clicked_at DESC
`

func (q *Queries) GetURLAnalytics(ctx context.Context, urlID uuid.UUID) ([]UrlClick, error) {
	rows, err := q.db.QueryContext(ctx, getURLAnalytics, urlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UrlClick
	for rows.Next() {
		var i UrlClick
		if err := rows.Scan(
			&i.ID,
			&i.UrlID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Referer,
			&i.Country,
			&i.City,
			&i.DeviceType,
			&i.Browser,
			&i.Os,
			&i.IsBot,
			&i.ClickedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAnalytics = `-- name: GetUserAnalytics :many
SELECT uc.id, uc.url_id, uc.ip_address, uc.user_agent, uc.referer, uc.country, uc.city, uc.device_type, uc.browser, uc.os, uc.is_bot, uc.clicked_at FROM url_clicks uc
JOIN urls u ON uc.url_id = u.id
WHERE u.user_id = $1
ORDER BY uc.clicked_at DESC
`

func (q *Queries) GetUserAnalytics(ctx context.Context, userID uuid.UUID) ([]UrlClick, error) {
	rows, err := q.db.QueryContext(ctx, getUserAnalytics, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UrlClick
	for rows.Next() {
		var i UrlClick
		if err := rows.Scan(
			&i.ID,
			&i.UrlID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Referer,
			&i.Country,
			&i.City,
			&i.DeviceType,
			&i.Browser,
			&i.Os,
			&i.IsBot,
			&i.ClickedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
