// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createClick = `-- name: CreateClick :one
INSERT INTO url_clicks (url_id, ip_address, user_agent, referer, country, city, device_type, browser, os, is_bot)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, url_id, ip_address, user_agent, referer, country, city, device_type, browser, os, is_bot, clicked_at
`

type CreateClickParams struct {
	UrlID      uuid.UUID      `json:"url_id"`
	IpAddress  pqtype.Inet    `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
	Referer    sql.NullString `json:"referer"`
	Country    sql.NullString `json:"country"`
	City       sql.NullString `json:"city"`
	DeviceType sql.NullString `json:"device_type"`
	Browser    sql.NullString `json:"browser"`
	Os         sql.NullString `json:"os"`
	IsBot      sql.NullBool   `json:"is_bot"`
}

func (q *Queries) CreateClick(ctx context.Context, arg CreateClickParams) (UrlClick, error) {
	row := q.db.QueryRowContext(ctx, createClick,
		arg.UrlID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Referer,
		arg.Country,
		arg.City,
		arg.DeviceType,
		arg.Browser,
		arg.Os,
		arg.IsBot,
	)
	var i UrlClick
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.IpAddress,
		&i.UserAgent,
		&i.Referer,
		&i.Country,
		&i.City,
		&i.DeviceType,
		&i.Browser,
		&i.Os,
		&i.IsBot,
		&i.ClickedAt,
	)
	return i, err
}

const deleteOldAnalytics = `-- name: DeleteOldAnalytics :exec
DELETE FROM url_clicks
WHERE url_id IN (
    SELECT id FROM urls WHERE user_id = $1
)
AND clicked_at < $2
`

type DeleteOldAnalyticsParams struct {
	UserID    uuid.UUID    `json:"user_id"`
	ClickedAt sql.NullTime `json:"clicked_at"`
}

func (q *Queries) DeleteOldAnalytics(ctx context.Context, arg DeleteOldAnalyticsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOldAnalytics, arg.UserID, arg.ClickedAt)
	return err
}

const getMonthlyClickStats = `-- name: GetMonthlyClickStats :one
SELECT
    COUNT(*) as monthly_clicks
FROM url_clicks uc
JOIN urls u ON uc.url_id = u.id
WHERE u.user_id = $1
    AND DATE_TRUNC('month', uc.clicked_at) = DATE_TRUNC('month', CURRENT_DATE)
`

func (q *Queries) GetMonthlyClickStats(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyClickStats, userID)
	var monthly_clicks int64
	err := row.Scan(&monthly_clicks)
	return monthly_clicks, err
}

const getURLAnalytics = `-- name: GetURLAnalytics :many
SELECT id, url_id, ip_address, user_agent, referer, country, city, device_type, browser, os, is_bot, clicked_at FROM url_clicks WHERE url_id = $1
ORDER BY clicked_at DESC
`

func (q *Queries) GetURLAnalytics(ctx context.Context, urlID uuid.UUID) ([]UrlClick, error) {
	rows, err := q.db.QueryContext(ctx, getURLAnalytics, urlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UrlClick
	for rows.Next() {
		var i UrlClick
		if err := rows.Scan(
			&i.ID,
			&i.UrlID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Referer,
			&i.Country,
			&i.City,
			&i.DeviceType,
			&i.Browser,
			&i.Os,
			&i.IsBot,
			&i.ClickedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getURLClicksByBrowser = `-- name: GetURLClicksByBrowser :many
SELECT 
    browser,
    COUNT(*) as clicks
FROM url_clicks
WHERE url_id = $1 AND browser IS NOT NULL
GROUP BY browser
ORDER BY clicks DESC
`

type GetURLClicksByBrowserRow struct {
	Browser sql.NullString `json:"browser"`
	Clicks  int64          `json:"clicks"`
}

func (q *Queries) GetURLClicksByBrowser(ctx context.Context, urlID uuid.UUID) ([]GetURLClicksByBrowserRow, error) {
	rows, err := q.db.QueryContext(ctx, getURLClicksByBrowser, urlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetURLClicksByBrowserRow
	for rows.Next() {
		var i GetURLClicksByBrowserRow
		if err := rows.Scan(&i.Browser, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getURLClicksByDate = `-- name: GetURLClicksByDate :many
SELECT 
    DATE(clicked_at) as date,
    COUNT(*) as clicks
FROM url_clicks
WHERE url_id = $1
GROUP BY DATE(clicked_at)
ORDER BY date DESC
`

type GetURLClicksByDateRow struct {
	Date   time.Time `json:"date"`
	Clicks int64     `json:"clicks"`
}

func (q *Queries) GetURLClicksByDate(ctx context.Context, urlID uuid.UUID) ([]GetURLClicksByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getURLClicksByDate, urlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetURLClicksByDateRow
	for rows.Next() {
		var i GetURLClicksByDateRow
		if err := rows.Scan(&i.Date, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getURLClicksByDevice = `-- name: GetURLClicksByDevice :many
SELECT 
    device_type,
    COUNT(*) as clicks
FROM url_clicks
WHERE url_id = $1 AND device_type IS NOT NULL
GROUP BY device_type
ORDER BY clicks DESC
`

type GetURLClicksByDeviceRow struct {
	DeviceType sql.NullString `json:"device_type"`
	Clicks     int64          `json:"clicks"`
}

func (q *Queries) GetURLClicksByDevice(ctx context.Context, urlID uuid.UUID) ([]GetURLClicksByDeviceRow, error) {
	rows, err := q.db.QueryContext(ctx, getURLClicksByDevice, urlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetURLClicksByDeviceRow
	for rows.Next() {
		var i GetURLClicksByDeviceRow
		if err := rows.Scan(&i.DeviceType, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getURLClicksByReferrerAndDate = `-- name: GetURLClicksByReferrerAndDate :many
SELECT
    DATE(clicked_at) as date,
    referer,
    COUNT(*) as clicks
FROM url_clicks
WHERE url_id = $1
GROUP BY DATE(clicked_at), referer
ORDER BY date DESC, clicks DESC
`

type GetURLClicksByReferrerAndDateRow struct {
	Date    time.Time      `json:"date"`
	Referer sql.NullString `json:"referer"`
	Clicks  int64          `json:"clicks"`
}

func (q *Queries) GetURLClicksByReferrerAndDate(ctx context.Context, urlID uuid.UUID) ([]GetURLClicksByReferrerAndDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getURLClicksByReferrerAndDate, urlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetURLClicksByReferrerAndDateRow
	for rows.Next() {
		var i GetURLClicksByReferrerAndDateRow
		if err := rows.Scan(&i.Date, &i.Referer, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAnalytics = `-- name: GetUserAnalytics :many
SELECT uc.id, uc.url_id, uc.ip_address, uc.user_agent, uc.referer, uc.country, uc.city, uc.device_type, uc.browser, uc.os, uc.is_bot, uc.clicked_at FROM url_clicks uc
JOIN urls u ON uc.url_id = u.id
WHERE u.user_id = $1
ORDER BY uc.clicked_at DESC
`

func (q *Queries) GetUserAnalytics(ctx context.Context, userID uuid.UUID) ([]UrlClick, error) {
	rows, err := q.db.QueryContext(ctx, getUserAnalytics, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UrlClick
	for rows.Next() {
		var i UrlClick
		if err := rows.Scan(
			&i.ID,
			&i.UrlID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Referer,
			&i.Country,
			&i.City,
			&i.DeviceType,
			&i.Browser,
			&i.Os,
			&i.IsBot,
			&i.ClickedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserClickStats = `-- name: GetUserClickStats :one
SELECT 
    COUNT(*) as total_clicks,
    COUNT(DISTINCT uc.url_id) as unique_urls_clicked,
    COUNT(DISTINCT uc.country) as unique_countries,
    COUNT(DISTINCT uc.city) as unique_cities
FROM url_clicks uc
JOIN urls u ON uc.url_id = u.id
WHERE u.user_id = $1
`

type GetUserClickStatsRow struct {
	TotalClicks       int64 `json:"total_clicks"`
	UniqueUrlsClicked int64 `json:"unique_urls_clicked"`
	UniqueCountries   int64 `json:"unique_countries"`
	UniqueCities      int64 `json:"unique_cities"`
}

func (q *Queries) GetUserClickStats(ctx context.Context, userID uuid.UUID) (GetUserClickStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserClickStats, userID)
	var i GetUserClickStatsRow
	err := row.Scan(
		&i.TotalClicks,
		&i.UniqueUrlsClicked,
		&i.UniqueCountries,
		&i.UniqueCities,
	)
	return i, err
}

const getUserClicksByBrowser = `-- name: GetUserClicksByBrowser :many
SELECT 
    browser,
    COUNT(*) as clicks
FROM url_clicks uc
JOIN urls u ON uc.url_id = u.id
WHERE u.user_id = $1 AND uc.browser IS NOT NULL
GROUP BY browser
ORDER BY clicks DESC
LIMIT 10
`

type GetUserClicksByBrowserRow struct {
	Browser sql.NullString `json:"browser"`
	Clicks  int64          `json:"clicks"`
}

func (q *Queries) GetUserClicksByBrowser(ctx context.Context, userID uuid.UUID) ([]GetUserClicksByBrowserRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserClicksByBrowser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserClicksByBrowserRow
	for rows.Next() {
		var i GetUserClicksByBrowserRow
		if err := rows.Scan(&i.Browser, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserClicksByCountry = `-- name: GetUserClicksByCountry :many
SELECT 
    country,
    COUNT(*) as clicks
FROM url_clicks uc
JOIN urls u ON uc.url_id = u.id
WHERE u.user_id = $1 AND uc.country IS NOT NULL
GROUP BY country
ORDER BY clicks DESC
LIMIT 10
`

type GetUserClicksByCountryRow struct {
	Country sql.NullString `json:"country"`
	Clicks  int64          `json:"clicks"`
}

func (q *Queries) GetUserClicksByCountry(ctx context.Context, userID uuid.UUID) ([]GetUserClicksByCountryRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserClicksByCountry, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserClicksByCountryRow
	for rows.Next() {
		var i GetUserClicksByCountryRow
		if err := rows.Scan(&i.Country, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserClicksByDate = `-- name: GetUserClicksByDate :many
SELECT
    DATE(clicked_at) as date,
    COUNT(*) as clicks
FROM url_clicks uc
JOIN urls u ON uc.url_id = u.id
WHERE u.user_id = $1
GROUP BY DATE(clicked_at)
ORDER BY date DESC
LIMIT 30
`

type GetUserClicksByDateRow struct {
	Date   time.Time `json:"date"`
	Clicks int64     `json:"clicks"`
}

func (q *Queries) GetUserClicksByDate(ctx context.Context, userID uuid.UUID) ([]GetUserClicksByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserClicksByDate, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserClicksByDateRow
	for rows.Next() {
		var i GetUserClicksByDateRow
		if err := rows.Scan(&i.Date, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserClicksByDevice = `-- name: GetUserClicksByDevice :many
SELECT 
    device_type,
    COUNT(*) as clicks
FROM url_clicks uc
JOIN urls u ON uc.url_id = u.id
WHERE u.user_id = $1 AND uc.device_type IS NOT NULL
GROUP BY device_type
ORDER BY clicks DESC
`

type GetUserClicksByDeviceRow struct {
	DeviceType sql.NullString `json:"device_type"`
	Clicks     int64          `json:"clicks"`
}

func (q *Queries) GetUserClicksByDevice(ctx context.Context, userID uuid.UUID) ([]GetUserClicksByDeviceRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserClicksByDevice, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserClicksByDeviceRow
	for rows.Next() {
		var i GetUserClicksByDeviceRow
		if err := rows.Scan(&i.DeviceType, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
