// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const cleanupExpiredAPIKeys = `-- name: CleanupExpiredAPIKeys :exec
DELETE FROM api_keys
WHERE expires_at IS NOT NULL AND expires_at < NOW()
`

func (q *Queries) CleanupExpiredAPIKeys(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredAPIKeys)
	return err
}

const countUserActiveAPIKeys = `-- name: CountUserActiveAPIKeys :one
SELECT COUNT(*) FROM api_keys
WHERE user_id = $1 AND is_active = TRUE
`

func (q *Queries) CountUserActiveAPIKeys(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserActiveAPIKeys, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    user_id,
    key_name,
    api_key_hash,
    api_key_prefix,
    permissions,
    rate_limit_tier,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, key_name, api_key_hash, api_key_prefix, permissions, rate_limit_tier, last_used_at, is_active, expires_at, created_at, updated_at
`

type CreateAPIKeyParams struct {
	UserID        uuid.UUID             `json:"user_id"`
	KeyName       string                `json:"key_name"`
	ApiKeyHash    string                `json:"api_key_hash"`
	ApiKeyPrefix  string                `json:"api_key_prefix"`
	Permissions   pqtype.NullRawMessage `json:"permissions"`
	RateLimitTier string                `json:"rate_limit_tier"`
	ExpiresAt     sql.NullTime          `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.UserID,
		arg.KeyName,
		arg.ApiKeyHash,
		arg.ApiKeyPrefix,
		arg.Permissions,
		arg.RateLimitTier,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyName,
		&i.ApiKeyHash,
		&i.ApiKeyPrefix,
		&i.Permissions,
		&i.RateLimitTier,
		&i.LastUsedAt,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAPIKey = `-- name: DeactivateAPIKey :exec
UPDATE api_keys
SET is_active = FALSE, updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type DeactivateAPIKeyParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeactivateAPIKey(ctx context.Context, arg DeactivateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, deactivateAPIKey, arg.ID, arg.UserID)
	return err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys
WHERE id = $1 AND user_id = $2
`

type DeleteAPIKeyParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, arg.ID, arg.UserID)
	return err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, user_id, key_name, api_key_hash, api_key_prefix, permissions, rate_limit_tier, last_used_at, is_active, expires_at, created_at, updated_at FROM api_keys
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetAPIKeyByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetAPIKeyByID(ctx context.Context, arg GetAPIKeyByIDParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByID, arg.ID, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyName,
		&i.ApiKeyHash,
		&i.ApiKeyPrefix,
		&i.Permissions,
		&i.RateLimitTier,
		&i.LastUsedAt,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, user_id, key_name, api_key_hash, api_key_prefix, permissions, rate_limit_tier, last_used_at, is_active, expires_at, created_at, updated_at FROM api_keys
WHERE api_key_prefix = $1 AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, apiKeyPrefix string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByPrefix, apiKeyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyName,
		&i.ApiKeyHash,
		&i.ApiKeyPrefix,
		&i.Permissions,
		&i.RateLimitTier,
		&i.LastUsedAt,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserAPIKeys = `-- name: ListUserAPIKeys :many
SELECT id, user_id, key_name, api_key_hash, api_key_prefix, permissions, rate_limit_tier, last_used_at, is_active, expires_at, created_at, updated_at FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserAPIKeys(ctx context.Context, userID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listUserAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyName,
			&i.ApiKeyHash,
			&i.ApiKeyPrefix,
			&i.Permissions,
			&i.RateLimitTier,
			&i.LastUsedAt,
			&i.IsActive,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, id)
	return err
}

const updateAPIKeyName = `-- name: UpdateAPIKeyName :one
UPDATE api_keys
SET key_name = $2, updated_at = NOW()
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, key_name, api_key_hash, api_key_prefix, permissions, rate_limit_tier, last_used_at, is_active, expires_at, created_at, updated_at
`

type UpdateAPIKeyNameParams struct {
	ID      uuid.UUID `json:"id"`
	KeyName string    `json:"key_name"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateAPIKeyName(ctx context.Context, arg UpdateAPIKeyNameParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, updateAPIKeyName, arg.ID, arg.KeyName, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyName,
		&i.ApiKeyHash,
		&i.ApiKeyPrefix,
		&i.Permissions,
		&i.RateLimitTier,
		&i.LastUsedAt,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAPIKeyPermissions = `-- name: UpdateAPIKeyPermissions :one
UPDATE api_keys
SET permissions = $2, updated_at = NOW()
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, key_name, api_key_hash, api_key_prefix, permissions, rate_limit_tier, last_used_at, is_active, expires_at, created_at, updated_at
`

type UpdateAPIKeyPermissionsParams struct {
	ID          uuid.UUID             `json:"id"`
	Permissions pqtype.NullRawMessage `json:"permissions"`
	UserID      uuid.UUID             `json:"user_id"`
}

func (q *Queries) UpdateAPIKeyPermissions(ctx context.Context, arg UpdateAPIKeyPermissionsParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, updateAPIKeyPermissions, arg.ID, arg.Permissions, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyName,
		&i.ApiKeyHash,
		&i.ApiKeyPrefix,
		&i.Permissions,
		&i.RateLimitTier,
		&i.LastUsedAt,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
