// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bio_pages.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const checkUsernameAvailability = `-- name: CheckUsernameAvailability :one
SELECT EXISTS(
    SELECT 1 FROM bio_pages WHERE username = $1
) AS exists
`

func (q *Queries) CheckUsernameAvailability(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUsernameAvailability, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createBioPage = `-- name: CreateBioPage :one

INSERT INTO bio_pages (
    user_id,
    username,
    display_name,
    bio,
    avatar_url,
    favicon_url,
    theme,
    custom_colors,
    background_type,
    background_value,
    button_style,
    font_family,
    social_links,
    links,
    seo_title,
    seo_description,
    og_image_url,
    is_published
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
) RETURNING id, user_id, username, display_name, bio, avatar_url, favicon_url, theme, custom_colors, background_type, background_value, button_style, font_family, social_links, links, seo_title, seo_description, og_image_url, is_published, subdomain, total_views, total_clicks, created_at, updated_at, last_published_at
`

type CreateBioPageParams struct {
	UserID          uuid.UUID
	Username        string
	DisplayName     string
	Bio             sql.NullString
	AvatarUrl       sql.NullString
	FaviconUrl      sql.NullString
	Theme           sql.NullString
	CustomColors    pqtype.NullRawMessage
	BackgroundType  sql.NullString
	BackgroundValue sql.NullString
	ButtonStyle     sql.NullString
	FontFamily      sql.NullString
	SocialLinks     pqtype.NullRawMessage
	Links           pqtype.NullRawMessage
	SeoTitle        sql.NullString
	SeoDescription  sql.NullString
	OgImageUrl      sql.NullString
	IsPublished     sql.NullBool
}

// Bio Pages CRUD Operations
func (q *Queries) CreateBioPage(ctx context.Context, arg CreateBioPageParams) (BioPage, error) {
	row := q.db.QueryRowContext(ctx, createBioPage,
		arg.UserID,
		arg.Username,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
		arg.FaviconUrl,
		arg.Theme,
		arg.CustomColors,
		arg.BackgroundType,
		arg.BackgroundValue,
		arg.ButtonStyle,
		arg.FontFamily,
		arg.SocialLinks,
		arg.Links,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.OgImageUrl,
		arg.IsPublished,
	)
	var i BioPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.FaviconUrl,
		&i.Theme,
		&i.CustomColors,
		&i.BackgroundType,
		&i.BackgroundValue,
		&i.ButtonStyle,
		&i.FontFamily,
		&i.SocialLinks,
		&i.Links,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgImageUrl,
		&i.IsPublished,
		&i.Subdomain,
		&i.TotalViews,
		&i.TotalClicks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPublishedAt,
	)
	return i, err
}

const deleteBioPage = `-- name: DeleteBioPage :exec
DELETE FROM bio_pages
WHERE username = $1 AND user_id = $2
`

type DeleteBioPageParams struct {
	Username string
	UserID   uuid.UUID
}

func (q *Queries) DeleteBioPage(ctx context.Context, arg DeleteBioPageParams) error {
	_, err := q.db.ExecContext(ctx, deleteBioPage, arg.Username, arg.UserID)
	return err
}

const getBioLinkClicksByLink = `-- name: GetBioLinkClicksByLink :many
SELECT
    link_id,
    COUNT(*) as clicks
FROM bio_link_clicks
WHERE bio_page_id = $1
    AND clicked_at >= $2
    AND clicked_at <= $3
GROUP BY link_id
ORDER BY clicks DESC
`

type GetBioLinkClicksByLinkParams struct {
	BioPageID   uuid.UUID
	ClickedAt   sql.NullTime
	ClickedAt_2 sql.NullTime
}

type GetBioLinkClicksByLinkRow struct {
	LinkID string
	Clicks int64
}

func (q *Queries) GetBioLinkClicksByLink(ctx context.Context, arg GetBioLinkClicksByLinkParams) ([]GetBioLinkClicksByLinkRow, error) {
	rows, err := q.db.QueryContext(ctx, getBioLinkClicksByLink, arg.BioPageID, arg.ClickedAt, arg.ClickedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBioLinkClicksByLinkRow
	for rows.Next() {
		var i GetBioLinkClicksByLinkRow
		if err := rows.Scan(&i.LinkID, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBioPageAnalytics = `-- name: GetBioPageAnalytics :one
SELECT
    COUNT(DISTINCT v.id) as total_views,
    COUNT(DISTINCT c.id) as total_clicks,
    COUNT(DISTINCT v.country) as unique_countries,
    COUNT(DISTINCT v.device) as unique_devices
FROM bio_pages bp
LEFT JOIN bio_page_views v ON v.bio_page_id = bp.id
LEFT JOIN bio_link_clicks c ON c.bio_page_id = bp.id
WHERE bp.username = $1 AND bp.user_id = $2
`

type GetBioPageAnalyticsParams struct {
	Username string
	UserID   uuid.UUID
}

type GetBioPageAnalyticsRow struct {
	TotalViews      int64
	TotalClicks     int64
	UniqueCountries int64
	UniqueDevices   int64
}

func (q *Queries) GetBioPageAnalytics(ctx context.Context, arg GetBioPageAnalyticsParams) (GetBioPageAnalyticsRow, error) {
	row := q.db.QueryRowContext(ctx, getBioPageAnalytics, arg.Username, arg.UserID)
	var i GetBioPageAnalyticsRow
	err := row.Scan(
		&i.TotalViews,
		&i.TotalClicks,
		&i.UniqueCountries,
		&i.UniqueDevices,
	)
	return i, err
}

const getBioPageBrowserStats = `-- name: GetBioPageBrowserStats :many
SELECT
    browser,
    COUNT(*) as count
FROM bio_page_views
WHERE bio_page_id = $1
GROUP BY browser
ORDER BY count DESC
`

type GetBioPageBrowserStatsRow struct {
	Browser sql.NullString
	Count   int64
}

func (q *Queries) GetBioPageBrowserStats(ctx context.Context, bioPageID uuid.UUID) ([]GetBioPageBrowserStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getBioPageBrowserStats, bioPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBioPageBrowserStatsRow
	for rows.Next() {
		var i GetBioPageBrowserStatsRow
		if err := rows.Scan(&i.Browser, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBioPageByUsername = `-- name: GetBioPageByUsername :one
SELECT id, user_id, username, display_name, bio, avatar_url, favicon_url, theme, custom_colors, background_type, background_value, button_style, font_family, social_links, links, seo_title, seo_description, og_image_url, is_published, subdomain, total_views, total_clicks, created_at, updated_at, last_published_at FROM bio_pages
WHERE username = $1 AND is_published = true
`

func (q *Queries) GetBioPageByUsername(ctx context.Context, username string) (BioPage, error) {
	row := q.db.QueryRowContext(ctx, getBioPageByUsername, username)
	var i BioPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.FaviconUrl,
		&i.Theme,
		&i.CustomColors,
		&i.BackgroundType,
		&i.BackgroundValue,
		&i.ButtonStyle,
		&i.FontFamily,
		&i.SocialLinks,
		&i.Links,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgImageUrl,
		&i.IsPublished,
		&i.Subdomain,
		&i.TotalViews,
		&i.TotalClicks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPublishedAt,
	)
	return i, err
}

const getBioPageByUsernameForEdit = `-- name: GetBioPageByUsernameForEdit :one
SELECT id, user_id, username, display_name, bio, avatar_url, favicon_url, theme, custom_colors, background_type, background_value, button_style, font_family, social_links, links, seo_title, seo_description, og_image_url, is_published, subdomain, total_views, total_clicks, created_at, updated_at, last_published_at FROM bio_pages
WHERE username = $1 AND user_id = $2
`

type GetBioPageByUsernameForEditParams struct {
	Username string
	UserID   uuid.UUID
}

func (q *Queries) GetBioPageByUsernameForEdit(ctx context.Context, arg GetBioPageByUsernameForEditParams) (BioPage, error) {
	row := q.db.QueryRowContext(ctx, getBioPageByUsernameForEdit, arg.Username, arg.UserID)
	var i BioPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.FaviconUrl,
		&i.Theme,
		&i.CustomColors,
		&i.BackgroundType,
		&i.BackgroundValue,
		&i.ButtonStyle,
		&i.FontFamily,
		&i.SocialLinks,
		&i.Links,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgImageUrl,
		&i.IsPublished,
		&i.Subdomain,
		&i.TotalViews,
		&i.TotalClicks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPublishedAt,
	)
	return i, err
}

const getBioPageCountryStats = `-- name: GetBioPageCountryStats :many
SELECT
    country,
    COUNT(*) as count
FROM bio_page_views
WHERE bio_page_id = $1
GROUP BY country
ORDER BY count DESC
LIMIT 10
`

type GetBioPageCountryStatsRow struct {
	Country sql.NullString
	Count   int64
}

func (q *Queries) GetBioPageCountryStats(ctx context.Context, bioPageID uuid.UUID) ([]GetBioPageCountryStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getBioPageCountryStats, bioPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBioPageCountryStatsRow
	for rows.Next() {
		var i GetBioPageCountryStatsRow
		if err := rows.Scan(&i.Country, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBioPageDeviceStats = `-- name: GetBioPageDeviceStats :many
SELECT
    device,
    COUNT(*) as count
FROM bio_page_views
WHERE bio_page_id = $1
GROUP BY device
ORDER BY count DESC
`

type GetBioPageDeviceStatsRow struct {
	Device sql.NullString
	Count  int64
}

func (q *Queries) GetBioPageDeviceStats(ctx context.Context, bioPageID uuid.UUID) ([]GetBioPageDeviceStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getBioPageDeviceStats, bioPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBioPageDeviceStatsRow
	for rows.Next() {
		var i GetBioPageDeviceStatsRow
		if err := rows.Scan(&i.Device, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBioPageRecentClicks = `-- name: GetBioPageRecentClicks :many
SELECT id, bio_page_id, link_id, ip_address, user_agent, referer, country, city, device, browser, os, is_bot, clicked_at
FROM bio_link_clicks
WHERE bio_page_id = $1
ORDER BY clicked_at DESC
LIMIT $2
`

type GetBioPageRecentClicksParams struct {
	BioPageID uuid.UUID
	Limit     int32
}

func (q *Queries) GetBioPageRecentClicks(ctx context.Context, arg GetBioPageRecentClicksParams) ([]BioLinkClick, error) {
	rows, err := q.db.QueryContext(ctx, getBioPageRecentClicks, arg.BioPageID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BioLinkClick
	for rows.Next() {
		var i BioLinkClick
		if err := rows.Scan(
			&i.ID,
			&i.BioPageID,
			&i.LinkID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Referer,
			&i.Country,
			&i.City,
			&i.Device,
			&i.Browser,
			&i.Os,
			&i.IsBot,
			&i.ClickedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBioPageRecentViews = `-- name: GetBioPageRecentViews :many
SELECT id, bio_page_id, ip_address, user_agent, referer, country, city, device, browser, os, is_bot, viewed_at
FROM bio_page_views
WHERE bio_page_id = $1
ORDER BY viewed_at DESC
LIMIT $2
`

type GetBioPageRecentViewsParams struct {
	BioPageID uuid.UUID
	Limit     int32
}

func (q *Queries) GetBioPageRecentViews(ctx context.Context, arg GetBioPageRecentViewsParams) ([]BioPageView, error) {
	rows, err := q.db.QueryContext(ctx, getBioPageRecentViews, arg.BioPageID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BioPageView
	for rows.Next() {
		var i BioPageView
		if err := rows.Scan(
			&i.ID,
			&i.BioPageID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Referer,
			&i.Country,
			&i.City,
			&i.Device,
			&i.Browser,
			&i.Os,
			&i.IsBot,
			&i.ViewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBioPageViewsByDate = `-- name: GetBioPageViewsByDate :many
SELECT
    DATE(viewed_at) as date,
    COUNT(*) as views
FROM bio_page_views
WHERE bio_page_id = $1
    AND viewed_at >= $2
    AND viewed_at <= $3
GROUP BY DATE(viewed_at)
ORDER BY date DESC
`

type GetBioPageViewsByDateParams struct {
	BioPageID  uuid.UUID
	ViewedAt   sql.NullTime
	ViewedAt_2 sql.NullTime
}

type GetBioPageViewsByDateRow struct {
	Date  time.Time
	Views int64
}

func (q *Queries) GetBioPageViewsByDate(ctx context.Context, arg GetBioPageViewsByDateParams) ([]GetBioPageViewsByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getBioPageViewsByDate, arg.BioPageID, arg.ViewedAt, arg.ViewedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBioPageViewsByDateRow
	for rows.Next() {
		var i GetBioPageViewsByDateRow
		if err := rows.Scan(&i.Date, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBioPages = `-- name: GetUserBioPages :many
SELECT id, user_id, username, display_name, bio, avatar_url, favicon_url, theme, custom_colors, background_type, background_value, button_style, font_family, social_links, links, seo_title, seo_description, og_image_url, is_published, subdomain, total_views, total_clicks, created_at, updated_at, last_published_at FROM bio_pages
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserBioPages(ctx context.Context, userID uuid.UUID) ([]BioPage, error) {
	rows, err := q.db.QueryContext(ctx, getUserBioPages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BioPage
	for rows.Next() {
		var i BioPage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.FaviconUrl,
			&i.Theme,
			&i.CustomColors,
			&i.BackgroundType,
			&i.BackgroundValue,
			&i.ButtonStyle,
			&i.FontFamily,
			&i.SocialLinks,
			&i.Links,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.OgImageUrl,
			&i.IsPublished,
			&i.Subdomain,
			&i.TotalViews,
			&i.TotalClicks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastPublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementBioPageClicks = `-- name: IncrementBioPageClicks :exec
UPDATE bio_pages
SET total_clicks = total_clicks + 1
WHERE id = $1
`

func (q *Queries) IncrementBioPageClicks(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementBioPageClicks, id)
	return err
}

const incrementBioPageViews = `-- name: IncrementBioPageViews :exec
UPDATE bio_pages
SET total_views = total_views + 1
WHERE id = $1
`

func (q *Queries) IncrementBioPageViews(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementBioPageViews, id)
	return err
}

const publishBioPage = `-- name: PublishBioPage :one
UPDATE bio_pages
SET
    is_published = true,
    last_published_at = NOW()
WHERE username = $1 AND user_id = $2
RETURNING id, user_id, username, display_name, bio, avatar_url, favicon_url, theme, custom_colors, background_type, background_value, button_style, font_family, social_links, links, seo_title, seo_description, og_image_url, is_published, subdomain, total_views, total_clicks, created_at, updated_at, last_published_at
`

type PublishBioPageParams struct {
	Username string
	UserID   uuid.UUID
}

func (q *Queries) PublishBioPage(ctx context.Context, arg PublishBioPageParams) (BioPage, error) {
	row := q.db.QueryRowContext(ctx, publishBioPage, arg.Username, arg.UserID)
	var i BioPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.FaviconUrl,
		&i.Theme,
		&i.CustomColors,
		&i.BackgroundType,
		&i.BackgroundValue,
		&i.ButtonStyle,
		&i.FontFamily,
		&i.SocialLinks,
		&i.Links,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgImageUrl,
		&i.IsPublished,
		&i.Subdomain,
		&i.TotalViews,
		&i.TotalClicks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPublishedAt,
	)
	return i, err
}

const trackBioLinkClick = `-- name: TrackBioLinkClick :one
INSERT INTO bio_link_clicks (
    bio_page_id,
    link_id,
    ip_address,
    user_agent,
    referer,
    country,
    city,
    device,
    browser,
    os,
    is_bot
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, bio_page_id, link_id, ip_address, user_agent, referer, country, city, device, browser, os, is_bot, clicked_at
`

type TrackBioLinkClickParams struct {
	BioPageID uuid.UUID
	LinkID    string
	IpAddress sql.NullString
	UserAgent sql.NullString
	Referer   sql.NullString
	Country   sql.NullString
	City      sql.NullString
	Device    sql.NullString
	Browser   sql.NullString
	Os        sql.NullString
	IsBot     sql.NullBool
}

func (q *Queries) TrackBioLinkClick(ctx context.Context, arg TrackBioLinkClickParams) (BioLinkClick, error) {
	row := q.db.QueryRowContext(ctx, trackBioLinkClick,
		arg.BioPageID,
		arg.LinkID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Referer,
		arg.Country,
		arg.City,
		arg.Device,
		arg.Browser,
		arg.Os,
		arg.IsBot,
	)
	var i BioLinkClick
	err := row.Scan(
		&i.ID,
		&i.BioPageID,
		&i.LinkID,
		&i.IpAddress,
		&i.UserAgent,
		&i.Referer,
		&i.Country,
		&i.City,
		&i.Device,
		&i.Browser,
		&i.Os,
		&i.IsBot,
		&i.ClickedAt,
	)
	return i, err
}

const trackBioPageView = `-- name: TrackBioPageView :one

INSERT INTO bio_page_views (
    bio_page_id,
    ip_address,
    user_agent,
    referer,
    country,
    city,
    device,
    browser,
    os,
    is_bot
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, bio_page_id, ip_address, user_agent, referer, country, city, device, browser, os, is_bot, viewed_at
`

type TrackBioPageViewParams struct {
	BioPageID uuid.UUID
	IpAddress sql.NullString
	UserAgent sql.NullString
	Referer   sql.NullString
	Country   sql.NullString
	City      sql.NullString
	Device    sql.NullString
	Browser   sql.NullString
	Os        sql.NullString
	IsBot     sql.NullBool
}

// Analytics Queries
func (q *Queries) TrackBioPageView(ctx context.Context, arg TrackBioPageViewParams) (BioPageView, error) {
	row := q.db.QueryRowContext(ctx, trackBioPageView,
		arg.BioPageID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Referer,
		arg.Country,
		arg.City,
		arg.Device,
		arg.Browser,
		arg.Os,
		arg.IsBot,
	)
	var i BioPageView
	err := row.Scan(
		&i.ID,
		&i.BioPageID,
		&i.IpAddress,
		&i.UserAgent,
		&i.Referer,
		&i.Country,
		&i.City,
		&i.Device,
		&i.Browser,
		&i.Os,
		&i.IsBot,
		&i.ViewedAt,
	)
	return i, err
}

const unpublishBioPage = `-- name: UnpublishBioPage :one
UPDATE bio_pages
SET is_published = false
WHERE username = $1 AND user_id = $2
RETURNING id, user_id, username, display_name, bio, avatar_url, favicon_url, theme, custom_colors, background_type, background_value, button_style, font_family, social_links, links, seo_title, seo_description, og_image_url, is_published, subdomain, total_views, total_clicks, created_at, updated_at, last_published_at
`

type UnpublishBioPageParams struct {
	Username string
	UserID   uuid.UUID
}

func (q *Queries) UnpublishBioPage(ctx context.Context, arg UnpublishBioPageParams) (BioPage, error) {
	row := q.db.QueryRowContext(ctx, unpublishBioPage, arg.Username, arg.UserID)
	var i BioPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.FaviconUrl,
		&i.Theme,
		&i.CustomColors,
		&i.BackgroundType,
		&i.BackgroundValue,
		&i.ButtonStyle,
		&i.FontFamily,
		&i.SocialLinks,
		&i.Links,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgImageUrl,
		&i.IsPublished,
		&i.Subdomain,
		&i.TotalViews,
		&i.TotalClicks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPublishedAt,
	)
	return i, err
}

const updateBioPage = `-- name: UpdateBioPage :one
UPDATE bio_pages
SET
    display_name = COALESCE($2, display_name),
    bio = COALESCE($3, bio),
    avatar_url = COALESCE($4, avatar_url),
    favicon_url = COALESCE($5, favicon_url),
    theme = COALESCE($6, theme),
    custom_colors = COALESCE($7, custom_colors),
    background_type = COALESCE($8, background_type),
    background_value = COALESCE($9, background_value),
    button_style = COALESCE($10, button_style),
    font_family = COALESCE($11, font_family),
    social_links = COALESCE($12, social_links),
    links = COALESCE($13, links),
    seo_title = COALESCE($14, seo_title),
    seo_description = COALESCE($15, seo_description),
    og_image_url = COALESCE($16, og_image_url),
    is_published = COALESCE($17, is_published),
    updated_at = NOW()
WHERE username = $1 AND user_id = $18
RETURNING id, user_id, username, display_name, bio, avatar_url, favicon_url, theme, custom_colors, background_type, background_value, button_style, font_family, social_links, links, seo_title, seo_description, og_image_url, is_published, subdomain, total_views, total_clicks, created_at, updated_at, last_published_at
`

type UpdateBioPageParams struct {
	Username        string
	DisplayName     string
	Bio             sql.NullString
	AvatarUrl       sql.NullString
	FaviconUrl      sql.NullString
	Theme           sql.NullString
	CustomColors    pqtype.NullRawMessage
	BackgroundType  sql.NullString
	BackgroundValue sql.NullString
	ButtonStyle     sql.NullString
	FontFamily      sql.NullString
	SocialLinks     pqtype.NullRawMessage
	Links           pqtype.NullRawMessage
	SeoTitle        sql.NullString
	SeoDescription  sql.NullString
	OgImageUrl      sql.NullString
	IsPublished     sql.NullBool
	UserID          uuid.UUID
}

func (q *Queries) UpdateBioPage(ctx context.Context, arg UpdateBioPageParams) (BioPage, error) {
	row := q.db.QueryRowContext(ctx, updateBioPage,
		arg.Username,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
		arg.FaviconUrl,
		arg.Theme,
		arg.CustomColors,
		arg.BackgroundType,
		arg.BackgroundValue,
		arg.ButtonStyle,
		arg.FontFamily,
		arg.SocialLinks,
		arg.Links,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.OgImageUrl,
		arg.IsPublished,
		arg.UserID,
	)
	var i BioPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.FaviconUrl,
		&i.Theme,
		&i.CustomColors,
		&i.BackgroundType,
		&i.BackgroundValue,
		&i.ButtonStyle,
		&i.FontFamily,
		&i.SocialLinks,
		&i.Links,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgImageUrl,
		&i.IsPublished,
		&i.Subdomain,
		&i.TotalViews,
		&i.TotalClicks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPublishedAt,
	)
	return i, err
}
