// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocked_urls.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const blockURL = `-- name: BlockURL :one
INSERT INTO blocked_urls (short_id, original_url, block_reason, blocked_by, abuse_report_ref)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (short_id) DO UPDATE SET
    block_reason = EXCLUDED.block_reason,
    abuse_report_ref = EXCLUDED.abuse_report_ref,
    blocked_by = EXCLUDED.blocked_by,
    created_at = NOW()
RETURNING id, short_id, original_url, block_reason, blocked_by, abuse_report_ref, created_at
`

type BlockURLParams struct {
	ShortID        string         `json:"short_id"`
	OriginalUrl    sql.NullString `json:"original_url"`
	BlockReason    string         `json:"block_reason"`
	BlockedBy      uuid.NullUUID  `json:"blocked_by"`
	AbuseReportRef sql.NullString `json:"abuse_report_ref"`
}

// Admin: Block a URL by short_id (for abuse reports)
func (q *Queries) BlockURL(ctx context.Context, arg BlockURLParams) (BlockedUrl, error) {
	row := q.db.QueryRowContext(ctx, blockURL,
		arg.ShortID,
		arg.OriginalUrl,
		arg.BlockReason,
		arg.BlockedBy,
		arg.AbuseReportRef,
	)
	var i BlockedUrl
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.OriginalUrl,
		&i.BlockReason,
		&i.BlockedBy,
		&i.AbuseReportRef,
		&i.CreatedAt,
	)
	return i, err
}

const getBlockedURL = `-- name: GetBlockedURL :one
SELECT id, short_id, original_url, block_reason, blocked_by, abuse_report_ref, created_at FROM blocked_urls WHERE short_id = $1
`

// Get blocked URL details
func (q *Queries) GetBlockedURL(ctx context.Context, shortID string) (BlockedUrl, error) {
	row := q.db.QueryRowContext(ctx, getBlockedURL, shortID)
	var i BlockedUrl
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.OriginalUrl,
		&i.BlockReason,
		&i.BlockedBy,
		&i.AbuseReportRef,
		&i.CreatedAt,
	)
	return i, err
}

const getBlockedURLCount = `-- name: GetBlockedURLCount :one
SELECT COUNT(*) FROM blocked_urls
`

// Count total blocked URLs
func (q *Queries) GetBlockedURLCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBlockedURLCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isURLBlocked = `-- name: IsURLBlocked :one
SELECT EXISTS(SELECT 1 FROM blocked_urls WHERE short_id = $1) AS is_blocked
`

// Check if a URL is blocked (used during resolution)
func (q *Queries) IsURLBlocked(ctx context.Context, shortID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isURLBlocked, shortID)
	var is_blocked bool
	err := row.Scan(&is_blocked)
	return is_blocked, err
}

const listBlockedURLs = `-- name: ListBlockedURLs :many
SELECT id, short_id, original_url, block_reason, blocked_by, abuse_report_ref, created_at FROM blocked_urls ORDER BY created_at DESC
`

// List all blocked URLs (admin view)
func (q *Queries) ListBlockedURLs(ctx context.Context) ([]BlockedUrl, error) {
	rows, err := q.db.QueryContext(ctx, listBlockedURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockedUrl
	for rows.Next() {
		var i BlockedUrl
		if err := rows.Scan(
			&i.ID,
			&i.ShortID,
			&i.OriginalUrl,
			&i.BlockReason,
			&i.BlockedBy,
			&i.AbuseReportRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockURL = `-- name: UnblockURL :exec
DELETE FROM blocked_urls WHERE short_id = $1
`

// Admin: Unblock a URL
func (q *Queries) UnblockURL(ctx context.Context, shortID string) error {
	_, err := q.db.ExecContext(ctx, unblockURL, shortID)
	return err
}
