// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type BioLinkClick struct {
	ID        uuid.UUID      `json:"id"`
	BioPageID uuid.UUID      `json:"bio_page_id"`
	LinkID    string         `json:"link_id"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	Referer   sql.NullString `json:"referer"`
	Country   sql.NullString `json:"country"`
	City      sql.NullString `json:"city"`
	Device    sql.NullString `json:"device"`
	Browser   sql.NullString `json:"browser"`
	Os        sql.NullString `json:"os"`
	IsBot     sql.NullBool   `json:"is_bot"`
	ClickedAt sql.NullTime   `json:"clicked_at"`
}

type BioPage struct {
	ID              uuid.UUID             `json:"id"`
	UserID          uuid.UUID             `json:"user_id"`
	Username        string                `json:"username"`
	DisplayName     string                `json:"display_name"`
	Bio             sql.NullString        `json:"bio"`
	AvatarUrl       sql.NullString        `json:"avatar_url"`
	FaviconUrl      sql.NullString        `json:"favicon_url"`
	Theme           sql.NullString        `json:"theme"`
	CustomColors    pqtype.NullRawMessage `json:"custom_colors"`
	BackgroundType  sql.NullString        `json:"background_type"`
	BackgroundValue sql.NullString        `json:"background_value"`
	ButtonStyle     sql.NullString        `json:"button_style"`
	FontFamily      sql.NullString        `json:"font_family"`
	SocialLinks     pqtype.NullRawMessage `json:"social_links"`
	Links           pqtype.NullRawMessage `json:"links"`
	SeoTitle        sql.NullString        `json:"seo_title"`
	SeoDescription  sql.NullString        `json:"seo_description"`
	OgImageUrl      sql.NullString        `json:"og_image_url"`
	IsPublished     sql.NullBool          `json:"is_published"`
	Subdomain       sql.NullString        `json:"subdomain"`
	TotalViews      sql.NullInt32         `json:"total_views"`
	TotalClicks     sql.NullInt32         `json:"total_clicks"`
	CreatedAt       sql.NullTime          `json:"created_at"`
	UpdatedAt       sql.NullTime          `json:"updated_at"`
	LastPublishedAt sql.NullTime          `json:"last_published_at"`
}

type BioPageView struct {
	ID        uuid.UUID      `json:"id"`
	BioPageID uuid.UUID      `json:"bio_page_id"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	Referer   sql.NullString `json:"referer"`
	Country   sql.NullString `json:"country"`
	City      sql.NullString `json:"city"`
	Device    sql.NullString `json:"device"`
	Browser   sql.NullString `json:"browser"`
	Os        sql.NullString `json:"os"`
	IsBot     sql.NullBool   `json:"is_bot"`
	ViewedAt  sql.NullTime   `json:"viewed_at"`
}

type MonthlyUsage struct {
	ID              uuid.UUID    `json:"id"`
	UserID          uuid.UUID    `json:"user_id"`
	Month           string       `json:"month"`
	UrlCount        int32        `json:"url_count"`
	CustomLinkCount int32        `json:"custom_link_count"`
	QrCodeCount     int32        `json:"qr_code_count"`
	CreatedAt       sql.NullTime `json:"created_at"`
	UpdatedAt       sql.NullTime `json:"updated_at"`
}

type Subscription struct {
	ID                         uuid.UUID      `json:"id"`
	UserID                     uuid.UUID      `json:"user_id"`
	PlanID                     string         `json:"plan_id"`
	Status                     string         `json:"status"`
	CurrentPeriodStart         sql.NullTime   `json:"current_period_start"`
	CurrentPeriodEnd           sql.NullTime   `json:"current_period_end"`
	DodopaymentsSubscriptionID sql.NullString `json:"dodopayments_subscription_id"`
	DodopaymentsCustomerID     sql.NullString `json:"dodopayments_customer_id"`
	CreatedAt                  sql.NullTime   `json:"created_at"`
	UpdatedAt                  sql.NullTime   `json:"updated_at"`
	BillingInterval            sql.NullString `json:"billing_interval"`
	CancelAtPeriodEnd          sql.NullBool   `json:"cancel_at_period_end"`
	Currency                   sql.NullString `json:"currency"`
}

type Url struct {
	ID                  uuid.UUID      `json:"id"`
	UserID              uuid.UUID      `json:"user_id"`
	ShortID             string         `json:"short_id"`
	OriginalUrl         string         `json:"original_url"`
	Expiry              sql.NullTime   `json:"expiry"`
	IsActive            sql.NullBool   `json:"is_active"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	PasswordHash        sql.NullString `json:"password_hash"`
	IsLocked            sql.NullBool   `json:"is_locked"`
	PasswordAttempts    sql.NullInt32  `json:"password_attempts"`
	LastPasswordAttempt sql.NullTime   `json:"last_password_attempt"`
}

type UrlClick struct {
	ID         uuid.UUID      `json:"id"`
	UrlID      uuid.UUID      `json:"url_id"`
	IpAddress  pqtype.Inet    `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
	Referer    sql.NullString `json:"referer"`
	Country    sql.NullString `json:"country"`
	City       sql.NullString `json:"city"`
	DeviceType sql.NullString `json:"device_type"`
	Browser    sql.NullString `json:"browser"`
	Os         sql.NullString `json:"os"`
	IsBot      sql.NullBool   `json:"is_bot"`
	ClickedAt  sql.NullTime   `json:"clicked_at"`
}

type User struct {
	ID               uuid.UUID      `json:"id"`
	ClerkID          string         `json:"clerk_id"`
	Email            string         `json:"email"`
	FirstName        string         `json:"first_name"`
	LastName         string         `json:"last_name"`
	AvatarUrl        sql.NullString `json:"avatar_url"`
	SubscriptionTier string         `json:"subscription_tier"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	IsAdmin          sql.NullBool   `json:"is_admin"`
}

type Waitlist struct {
	ID        uuid.UUID    `json:"id"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
}
