// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type BioLinkClick struct {
	ID        uuid.UUID
	BioPageID uuid.UUID
	LinkID    string
	IpAddress sql.NullString
	UserAgent sql.NullString
	Referer   sql.NullString
	Country   sql.NullString
	City      sql.NullString
	Device    sql.NullString
	Browser   sql.NullString
	Os        sql.NullString
	IsBot     sql.NullBool
	ClickedAt sql.NullTime
}

type BioPage struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Username        string
	DisplayName     string
	Bio             sql.NullString
	AvatarUrl       sql.NullString
	FaviconUrl      sql.NullString
	Theme           sql.NullString
	CustomColors    pqtype.NullRawMessage
	BackgroundType  sql.NullString
	BackgroundValue sql.NullString
	ButtonStyle     sql.NullString
	FontFamily      sql.NullString
	SocialLinks     pqtype.NullRawMessage
	Links           pqtype.NullRawMessage
	SeoTitle        sql.NullString
	SeoDescription  sql.NullString
	OgImageUrl      sql.NullString
	IsPublished     sql.NullBool
	Subdomain       sql.NullString
	TotalViews      sql.NullInt32
	TotalClicks     sql.NullInt32
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	LastPublishedAt sql.NullTime
}

type BioPageView struct {
	ID        uuid.UUID
	BioPageID uuid.UUID
	IpAddress sql.NullString
	UserAgent sql.NullString
	Referer   sql.NullString
	Country   sql.NullString
	City      sql.NullString
	Device    sql.NullString
	Browser   sql.NullString
	Os        sql.NullString
	IsBot     sql.NullBool
	ViewedAt  sql.NullTime
}

type MonthlyUsage struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Month           string
	UrlCount        int32
	CustomLinkCount int32
	QrCodeCount     int32
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type Subscription struct {
	ID                         uuid.UUID
	UserID                     uuid.UUID
	PlanID                     string
	Status                     string
	CurrentPeriodStart         sql.NullTime
	CurrentPeriodEnd           sql.NullTime
	DodopaymentsSubscriptionID sql.NullString
	DodopaymentsCustomerID     sql.NullString
	CreatedAt                  sql.NullTime
	UpdatedAt                  sql.NullTime
	BillingInterval            sql.NullString
	CancelAtPeriodEnd          sql.NullBool
	Currency                   sql.NullString
}

type Url struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	ShortID             string
	OriginalUrl         string
	Expiry              sql.NullTime
	IsActive            sql.NullBool
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	PasswordHash        sql.NullString
	IsLocked            sql.NullBool
	PasswordAttempts    sql.NullInt32
	LastPasswordAttempt sql.NullTime
}

type UrlClick struct {
	ID         uuid.UUID
	UrlID      uuid.UUID
	IpAddress  pqtype.Inet
	UserAgent  sql.NullString
	Referer    sql.NullString
	Country    sql.NullString
	City       sql.NullString
	DeviceType sql.NullString
	Browser    sql.NullString
	Os         sql.NullString
	IsBot      sql.NullBool
	ClickedAt  sql.NullTime
}

type User struct {
	ID               uuid.UUID
	ClerkID          string
	Email            string
	FirstName        string
	LastName         string
	AvatarUrl        sql.NullString
	SubscriptionTier string
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	IsAdmin          sql.NullBool
}

type Waitlist struct {
	ID        uuid.UUID
	Email     string
	CreatedAt sql.NullTime
}
