// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monthly_usage.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getMonthlyUsage = `-- name: GetMonthlyUsage :one
SELECT id, user_id, month, url_count, custom_link_count, qr_code_count, created_at, updated_at FROM monthly_usage 
WHERE user_id = $1 AND month = $2
`

type GetMonthlyUsageParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  string    `json:"month"`
}

func (q *Queries) GetMonthlyUsage(ctx context.Context, arg GetMonthlyUsageParams) (MonthlyUsage, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyUsage, arg.UserID, arg.Month)
	var i MonthlyUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.UrlCount,
		&i.CustomLinkCount,
		&i.QrCodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementCustomLinkCount = `-- name: IncrementCustomLinkCount :one
INSERT INTO monthly_usage (user_id, month, custom_link_count)
VALUES ($1, $2, 1)
ON CONFLICT (user_id, month)
DO UPDATE SET custom_link_count = monthly_usage.custom_link_count + 1, updated_at = NOW()
RETURNING id, user_id, month, url_count, custom_link_count, qr_code_count, created_at, updated_at
`

type IncrementCustomLinkCountParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  string    `json:"month"`
}

func (q *Queries) IncrementCustomLinkCount(ctx context.Context, arg IncrementCustomLinkCountParams) (MonthlyUsage, error) {
	row := q.db.QueryRowContext(ctx, incrementCustomLinkCount, arg.UserID, arg.Month)
	var i MonthlyUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.UrlCount,
		&i.CustomLinkCount,
		&i.QrCodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementQRCodeCount = `-- name: IncrementQRCodeCount :one
INSERT INTO monthly_usage (user_id, month, qr_code_count)
VALUES ($1, $2, 1)
ON CONFLICT (user_id, month)
DO UPDATE SET qr_code_count = monthly_usage.qr_code_count + 1, updated_at = NOW()
RETURNING id, user_id, month, url_count, custom_link_count, qr_code_count, created_at, updated_at
`

type IncrementQRCodeCountParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  string    `json:"month"`
}

func (q *Queries) IncrementQRCodeCount(ctx context.Context, arg IncrementQRCodeCountParams) (MonthlyUsage, error) {
	row := q.db.QueryRowContext(ctx, incrementQRCodeCount, arg.UserID, arg.Month)
	var i MonthlyUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.UrlCount,
		&i.CustomLinkCount,
		&i.QrCodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementURLCount = `-- name: IncrementURLCount :one
INSERT INTO monthly_usage (user_id, month, url_count)
VALUES ($1, $2, 1)
ON CONFLICT (user_id, month) 
DO UPDATE SET url_count = monthly_usage.url_count + 1, updated_at = NOW()
RETURNING id, user_id, month, url_count, custom_link_count, qr_code_count, created_at, updated_at
`

type IncrementURLCountParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  string    `json:"month"`
}

func (q *Queries) IncrementURLCount(ctx context.Context, arg IncrementURLCountParams) (MonthlyUsage, error) {
	row := q.db.QueryRowContext(ctx, incrementURLCount, arg.UserID, arg.Month)
	var i MonthlyUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.UrlCount,
		&i.CustomLinkCount,
		&i.QrCodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
