// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (user_id, plan_id, status, dodopayments_customer_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, plan_id, status, current_period_start, current_period_end, dodopayments_subscription_id, dodopayments_customer_id, created_at, updated_at, billing_interval, cancel_at_period_end, currency
`

type CreateSubscriptionParams struct {
	UserID                 uuid.UUID
	PlanID                 string
	Status                 string
	DodopaymentsCustomerID sql.NullString
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.UserID,
		arg.PlanID,
		arg.Status,
		arg.DodopaymentsCustomerID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.DodopaymentsSubscriptionID,
		&i.DodopaymentsCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingInterval,
		&i.CancelAtPeriodEnd,
		&i.Currency,
	)
	return i, err
}

const getUserSubscription = `-- name: GetUserSubscription :one
SELECT id, user_id, plan_id, status, current_period_start, current_period_end, dodopayments_subscription_id, dodopayments_customer_id, created_at, updated_at, billing_interval, cancel_at_period_end, currency FROM subscriptions WHERE user_id = $1
`

func (q *Queries) GetUserSubscription(ctx context.Context, userID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getUserSubscription, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.DodopaymentsSubscriptionID,
		&i.DodopaymentsCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingInterval,
		&i.CancelAtPeriodEnd,
		&i.Currency,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, user_id, plan_id, status, current_period_start, current_period_end, dodopayments_subscription_id, dodopayments_customer_id, created_at, updated_at, billing_interval, cancel_at_period_end, currency FROM subscriptions ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.DodopaymentsSubscriptionID,
			&i.DodopaymentsCustomerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BillingInterval,
			&i.CancelAtPeriodEnd,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions 
SET plan_id = $2, status = $3, current_period_start = $4, current_period_end = $5, updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, plan_id, status, current_period_start, current_period_end, dodopayments_subscription_id, dodopayments_customer_id, created_at, updated_at, billing_interval, cancel_at_period_end, currency
`

type UpdateSubscriptionParams struct {
	UserID             uuid.UUID
	PlanID             string
	Status             string
	CurrentPeriodStart sql.NullTime
	CurrentPeriodEnd   sql.NullTime
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, updateSubscription,
		arg.UserID,
		arg.PlanID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.DodopaymentsSubscriptionID,
		&i.DodopaymentsCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingInterval,
		&i.CancelAtPeriodEnd,
		&i.Currency,
	)
	return i, err
}

const updateSubscriptionSetDPIDs = `-- name: UpdateSubscriptionSetDPIDs :one
UPDATE subscriptions
SET
  dodopayments_subscription_id = COALESCE($2, dodopayments_subscription_id),
  dodopayments_customer_id = COALESCE($3, dodopayments_customer_id),
  updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, plan_id, status, current_period_start, current_period_end, dodopayments_subscription_id, dodopayments_customer_id, created_at, updated_at, billing_interval, cancel_at_period_end, currency
`

type UpdateSubscriptionSetDPIDsParams struct {
	UserID                     uuid.UUID
	DodopaymentsSubscriptionID sql.NullString
	DodopaymentsCustomerID     sql.NullString
}

func (q *Queries) UpdateSubscriptionSetDPIDs(ctx context.Context, arg UpdateSubscriptionSetDPIDsParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, updateSubscriptionSetDPIDs, arg.UserID, arg.DodopaymentsSubscriptionID, arg.DodopaymentsCustomerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.DodopaymentsSubscriptionID,
		&i.DodopaymentsCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingInterval,
		&i.CancelAtPeriodEnd,
		&i.Currency,
	)
	return i, err
}
