// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (team_id, user_id)
VALUES ($1, $2)
RETURNING id, team_id, user_id, joined_at
`

type AddTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, addTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.JoinedAt,
	)
	return i, err
}

const assignURLToTeam = `-- name: AssignURLToTeam :exec
UPDATE urls
SET team_id = $1
WHERE id = $2
`

type AssignURLToTeamParams struct {
	TeamID uuid.NullUUID `json:"team_id"`
	ID     uuid.UUID     `json:"id"`
}

func (q *Queries) AssignURLToTeam(ctx context.Context, arg AssignURLToTeamParams) error {
	_, err := q.db.ExecContext(ctx, assignURLToTeam, arg.TeamID, arg.ID)
	return err
}

const canUserAccessURL = `-- name: CanUserAccessURL :one
SELECT EXISTS(
    SELECT 1 FROM urls u
    LEFT JOIN team_members tm ON u.team_id = tm.team_id
    WHERE u.id = $1
    AND (u.user_id = $2 OR tm.user_id = $2)
)
`

type CanUserAccessURLParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CanUserAccessURL(ctx context.Context, arg CanUserAccessURLParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, canUserAccessURL, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id, created_at, updated_at
`

type CreateTeamParams struct {
	Name    string    `json:"name"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.Name, arg.OwnerID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams
WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, owner_id, created_at, updated_at FROM teams
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByMemberUserID = `-- name: GetTeamByMemberUserID :one
SELECT t.id, t.name, t.owner_id, t.created_at, t.updated_at FROM teams t
JOIN team_members tm ON t.id = tm.team_id
WHERE tm.user_id = $1
LIMIT 1
`

func (q *Queries) GetTeamByMemberUserID(ctx context.Context, userID uuid.UUID) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByMemberUserID, userID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByOwnerID = `-- name: GetTeamByOwnerID :one
SELECT id, name, owner_id, created_at, updated_at FROM teams
WHERE owner_id = $1 LIMIT 1
`

func (q *Queries) GetTeamByOwnerID(ctx context.Context, ownerID uuid.UUID) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByOwnerID, ownerID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMemberCount = `-- name: GetTeamMemberCount :one
SELECT COUNT(*) FROM team_members
WHERE team_id = $1
`

func (q *Queries) GetTeamMemberCount(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTeamMemberCount, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTeamMembers = `-- name: GetTeamMembers :many
SELECT
    tm.id,
    tm.team_id,
    tm.user_id,
    tm.joined_at,
    u.email,
    u.clerk_id
FROM team_members tm
JOIN users u ON tm.user_id = u.id
WHERE tm.team_id = $1
ORDER BY tm.joined_at ASC
`

type GetTeamMembersRow struct {
	ID       uuid.UUID `json:"id"`
	TeamID   uuid.UUID `json:"team_id"`
	UserID   uuid.UUID `json:"user_id"`
	JoinedAt time.Time `json:"joined_at"`
	Email    string    `json:"email"`
	ClerkID  string    `json:"clerk_id"`
}

func (q *Queries) GetTeamMembers(ctx context.Context, teamID uuid.UUID) ([]GetTeamMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamMembersRow
	for rows.Next() {
		var i GetTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.JoinedAt,
			&i.Email,
			&i.ClerkID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamURLs = `-- name: GetTeamURLs :many
SELECT id, user_id, short_id, original_url, expiry, is_active, created_at, updated_at, password_hash, is_locked, password_attempts, last_password_attempt, team_id FROM urls
WHERE team_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTeamURLs(ctx context.Context, teamID uuid.NullUUID) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, getTeamURLs, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShortID,
			&i.OriginalUrl,
			&i.Expiry,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
			&i.IsLocked,
			&i.PasswordAttempts,
			&i.LastPasswordAttempt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserOwnedTeam = `-- name: GetUserOwnedTeam :one
SELECT id, name, owner_id, created_at, updated_at FROM teams
WHERE owner_id = $1
LIMIT 1
`

func (q *Queries) GetUserOwnedTeam(ctx context.Context, ownerID uuid.UUID) (Team, error) {
	row := q.db.QueryRowContext(ctx, getUserOwnedTeam, ownerID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTeams = `-- name: GetUserTeams :many
SELECT t.id, t.name, t.owner_id, t.created_at, t.updated_at FROM teams t
JOIN team_members tm ON t.id = tm.team_id
WHERE tm.user_id = $1
ORDER BY t.created_at DESC
`

func (q *Queries) GetUserTeams(ctx context.Context, userID uuid.UUID) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, getUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isTeamOwner = `-- name: IsTeamOwner :one
SELECT EXISTS(
    SELECT 1 FROM teams
    WHERE id = $1 AND owner_id = $2
)
`

type IsTeamOwnerParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) IsTeamOwner(ctx context.Context, arg IsTeamOwnerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTeamOwner, arg.ID, arg.OwnerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isUserInTeam = `-- name: IsUserInTeam :one
SELECT EXISTS(
    SELECT 1 FROM team_members
    WHERE team_id = $1 AND user_id = $2
)
`

type IsUserInTeamParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) IsUserInTeam(ctx context.Context, arg IsUserInTeamParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserInTeam, arg.TeamID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members
WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const unassignURLFromTeam = `-- name: UnassignURLFromTeam :exec
UPDATE urls
SET team_id = NULL
WHERE id = $1
`

func (q *Queries) UnassignURLFromTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, unassignURLFromTeam, id)
	return err
}

const updateTeamName = `-- name: UpdateTeamName :one
UPDATE teams
SET name = $1
WHERE id = $2
RETURNING id, name, owner_id, created_at, updated_at
`

type UpdateTeamNameParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateTeamName(ctx context.Context, arg UpdateTeamNameParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, updateTeamName, arg.Name, arg.ID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
