// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (user_id, short_id, original_url, expiry, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, short_id, original_url, expiry, is_active, created_at, updated_at
`

type CreateURLParams struct {
	UserID      uuid.UUID
	ShortID     string
	OriginalUrl string
	Expiry      sql.NullTime
	IsActive    sql.NullBool
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL,
		arg.UserID,
		arg.ShortID,
		arg.OriginalUrl,
		arg.Expiry,
		arg.IsActive,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortID,
		&i.OriginalUrl,
		&i.Expiry,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteURL = `-- name: DeleteURL :exec
UPDATE urls SET is_active = FALSE WHERE id = $1 AND user_id = $2
`

type DeleteURLParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteURL(ctx context.Context, arg DeleteURLParams) error {
	_, err := q.db.ExecContext(ctx, deleteURL, arg.ID, arg.UserID)
	return err
}

const getURLByShortID = `-- name: GetURLByShortID :one
SELECT id, user_id, short_id, original_url, expiry, is_active, created_at, updated_at FROM urls WHERE short_id = $1 AND is_active = TRUE
`

func (q *Queries) GetURLByShortID(ctx context.Context, shortID string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLByShortID, shortID)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortID,
		&i.OriginalUrl,
		&i.Expiry,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserURLs = `-- name: GetUserURLs :many
SELECT id, user_id, short_id, original_url, expiry, is_active, created_at, updated_at FROM urls WHERE user_id = $1 AND is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) GetUserURLs(ctx context.Context, userID uuid.UUID) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, getUserURLs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShortID,
			&i.OriginalUrl,
			&i.Expiry,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLs = `-- name: ListURLs :many
SELECT id, user_id, short_id, original_url, expiry, is_active, created_at, updated_at FROM urls ORDER BY created_at DESC
`

func (q *Queries) ListURLs(ctx context.Context) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, listURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShortID,
			&i.OriginalUrl,
			&i.Expiry,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateURL = `-- name: UpdateURL :one
UPDATE urls 
SET original_url = $2, expiry = $3, is_active = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, short_id, original_url, expiry, is_active, created_at, updated_at
`

type UpdateURLParams struct {
	ID          uuid.UUID
	OriginalUrl string
	Expiry      sql.NullTime
	IsActive    sql.NullBool
}

func (q *Queries) UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, updateURL,
		arg.ID,
		arg.OriginalUrl,
		arg.Expiry,
		arg.IsActive,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortID,
		&i.OriginalUrl,
		&i.Expiry,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
