// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (user_id, short_id, original_url, expiry, is_active, password_hash, is_locked)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, short_id, original_url, expiry, is_active, created_at, updated_at, password_hash, is_locked, password_attempts, last_password_attempt, team_id
`

type CreateURLParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	ShortID      string         `json:"short_id"`
	OriginalUrl  string         `json:"original_url"`
	Expiry       sql.NullTime   `json:"expiry"`
	IsActive     sql.NullBool   `json:"is_active"`
	PasswordHash sql.NullString `json:"password_hash"`
	IsLocked     sql.NullBool   `json:"is_locked"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL,
		arg.UserID,
		arg.ShortID,
		arg.OriginalUrl,
		arg.Expiry,
		arg.IsActive,
		arg.PasswordHash,
		arg.IsLocked,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortID,
		&i.OriginalUrl,
		&i.Expiry,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.IsLocked,
		&i.PasswordAttempts,
		&i.LastPasswordAttempt,
		&i.TeamID,
	)
	return i, err
}

const deactivateExpiredURLs = `-- name: DeactivateExpiredURLs :exec
UPDATE urls
SET is_active = FALSE, updated_at = NOW()
WHERE expiry IS NOT NULL
    AND expiry < $1
    AND is_active = TRUE
`

func (q *Queries) DeactivateExpiredURLs(ctx context.Context, expiry sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, deactivateExpiredURLs, expiry)
	return err
}

const deleteURL = `-- name: DeleteURL :exec
UPDATE urls SET is_active = FALSE WHERE id = $1 AND user_id = $2
`

type DeleteURLParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteURL(ctx context.Context, arg DeleteURLParams) error {
	_, err := q.db.ExecContext(ctx, deleteURL, arg.ID, arg.UserID)
	return err
}

const getMonthlyURLCount = `-- name: GetMonthlyURLCount :one
SELECT COUNT(*) FROM urls
WHERE user_id = $1
    AND is_active = TRUE
    AND DATE_TRUNC('month', created_at) = DATE_TRUNC('month', CURRENT_DATE)
`

func (q *Queries) GetMonthlyURLCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyURLCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getURL = `-- name: GetURL :one
SELECT id, user_id, short_id, original_url, expiry, is_active, created_at, updated_at, password_hash, is_locked, password_attempts, last_password_attempt, team_id FROM urls WHERE id = $1
`

func (q *Queries) GetURL(ctx context.Context, id uuid.UUID) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURL, id)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortID,
		&i.OriginalUrl,
		&i.Expiry,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.IsLocked,
		&i.PasswordAttempts,
		&i.LastPasswordAttempt,
		&i.TeamID,
	)
	return i, err
}

const getURLByShortID = `-- name: GetURLByShortID :one
SELECT id, user_id, short_id, original_url, expiry, is_active, created_at, updated_at, password_hash, is_locked, password_attempts, last_password_attempt, team_id FROM urls WHERE short_id = $1 AND is_active = TRUE
`

func (q *Queries) GetURLByShortID(ctx context.Context, shortID string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLByShortID, shortID)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortID,
		&i.OriginalUrl,
		&i.Expiry,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.IsLocked,
		&i.PasswordAttempts,
		&i.LastPasswordAttempt,
		&i.TeamID,
	)
	return i, err
}

const getUserURLByOriginalURL = `-- name: GetUserURLByOriginalURL :one
SELECT id, user_id, short_id, original_url, expiry, is_active, created_at, updated_at, password_hash, is_locked, password_attempts, last_password_attempt, team_id FROM urls
WHERE user_id = $1
    AND original_url = $2
    AND is_active = TRUE
LIMIT 1
`

type GetUserURLByOriginalURLParams struct {
	UserID      uuid.UUID `json:"user_id"`
	OriginalUrl string    `json:"original_url"`
}

func (q *Queries) GetUserURLByOriginalURL(ctx context.Context, arg GetUserURLByOriginalURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, getUserURLByOriginalURL, arg.UserID, arg.OriginalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortID,
		&i.OriginalUrl,
		&i.Expiry,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.IsLocked,
		&i.PasswordAttempts,
		&i.LastPasswordAttempt,
		&i.TeamID,
	)
	return i, err
}

const getUserURLCount = `-- name: GetUserURLCount :one
SELECT COUNT(*) FROM urls WHERE user_id = $1 AND is_active = TRUE
`

func (q *Queries) GetUserURLCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserURLCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserURLs = `-- name: GetUserURLs :many
SELECT id, user_id, short_id, original_url, expiry, is_active, created_at, updated_at, password_hash, is_locked, password_attempts, last_password_attempt, team_id FROM urls WHERE user_id = $1 AND is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) GetUserURLs(ctx context.Context, userID uuid.UUID) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, getUserURLs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShortID,
			&i.OriginalUrl,
			&i.Expiry,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
			&i.IsLocked,
			&i.PasswordAttempts,
			&i.LastPasswordAttempt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPasswordAttempts = `-- name: IncrementPasswordAttempts :exec
UPDATE urls
SET password_attempts = password_attempts + 1, last_password_attempt = NOW()
WHERE short_id = $1
`

func (q *Queries) IncrementPasswordAttempts(ctx context.Context, shortID string) error {
	_, err := q.db.ExecContext(ctx, incrementPasswordAttempts, shortID)
	return err
}

const listURLs = `-- name: ListURLs :many
SELECT id, user_id, short_id, original_url, expiry, is_active, created_at, updated_at, password_hash, is_locked, password_attempts, last_password_attempt, team_id FROM urls ORDER BY created_at DESC
`

func (q *Queries) ListURLs(ctx context.Context) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, listURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShortID,
			&i.OriginalUrl,
			&i.Expiry,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
			&i.IsLocked,
			&i.PasswordAttempts,
			&i.LastPasswordAttempt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeURLPassword = `-- name: RemoveURLPassword :one
UPDATE urls
SET password_hash = NULL, is_locked = FALSE, password_attempts = 0, last_password_attempt = NULL, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, short_id, original_url, expiry, is_active, created_at, updated_at, password_hash, is_locked, password_attempts, last_password_attempt, team_id
`

func (q *Queries) RemoveURLPassword(ctx context.Context, id uuid.UUID) (Url, error) {
	row := q.db.QueryRowContext(ctx, removeURLPassword, id)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortID,
		&i.OriginalUrl,
		&i.Expiry,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.IsLocked,
		&i.PasswordAttempts,
		&i.LastPasswordAttempt,
		&i.TeamID,
	)
	return i, err
}

const resetPasswordAttempts = `-- name: ResetPasswordAttempts :exec
UPDATE urls
SET password_attempts = 0, last_password_attempt = NULL
WHERE short_id = $1
`

func (q *Queries) ResetPasswordAttempts(ctx context.Context, shortID string) error {
	_, err := q.db.ExecContext(ctx, resetPasswordAttempts, shortID)
	return err
}

const setURLPassword = `-- name: SetURLPassword :one
UPDATE urls
SET password_hash = $2, is_locked = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, short_id, original_url, expiry, is_active, created_at, updated_at, password_hash, is_locked, password_attempts, last_password_attempt, team_id
`

type SetURLPasswordParams struct {
	ID           uuid.UUID      `json:"id"`
	PasswordHash sql.NullString `json:"password_hash"`
	IsLocked     sql.NullBool   `json:"is_locked"`
}

func (q *Queries) SetURLPassword(ctx context.Context, arg SetURLPasswordParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, setURLPassword, arg.ID, arg.PasswordHash, arg.IsLocked)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortID,
		&i.OriginalUrl,
		&i.Expiry,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.IsLocked,
		&i.PasswordAttempts,
		&i.LastPasswordAttempt,
		&i.TeamID,
	)
	return i, err
}

const updateURL = `-- name: UpdateURL :one
UPDATE urls 
SET original_url = $2, expiry = $3, is_active = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, short_id, original_url, expiry, is_active, created_at, updated_at, password_hash, is_locked, password_attempts, last_password_attempt, team_id
`

type UpdateURLParams struct {
	ID          uuid.UUID    `json:"id"`
	OriginalUrl string       `json:"original_url"`
	Expiry      sql.NullTime `json:"expiry"`
	IsActive    sql.NullBool `json:"is_active"`
}

func (q *Queries) UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, updateURL,
		arg.ID,
		arg.OriginalUrl,
		arg.Expiry,
		arg.IsActive,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortID,
		&i.OriginalUrl,
		&i.Expiry,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.IsLocked,
		&i.PasswordAttempts,
		&i.LastPasswordAttempt,
		&i.TeamID,
	)
	return i, err
}
