// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (clerk_id, email, first_name, last_name, avatar_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, clerk_id, email, first_name, last_name, avatar_url, subscription_tier, created_at, updated_at, is_admin
`

type CreateUserParams struct {
	ClerkID   string         `json:"clerk_id"`
	Email     string         `json:"email"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ClerkID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.SubscriptionTier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE clerk_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, clerkID string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, clerkID)
	return err
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, clerk_id, email, first_name, last_name, avatar_url, subscription_tier, created_at, updated_at, is_admin FROM users WHERE clerk_id = $1
`

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByClerkID, clerkID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.SubscriptionTier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, clerk_id, email, first_name, last_name, avatar_url, subscription_tier, created_at, updated_at, is_admin FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.SubscriptionTier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, clerk_id, email, first_name, last_name, avatar_url, subscription_tier, created_at, updated_at, is_admin FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.SubscriptionTier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, clerk_id, email, first_name, last_name, avatar_url, subscription_tier, created_at, updated_at, is_admin FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ClerkID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
			&i.SubscriptionTier,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET email = $2, first_name = $3, last_name = $4, avatar_url = $5, updated_at = NOW()
WHERE clerk_id = $1
RETURNING id, clerk_id, email, first_name, last_name, avatar_url, subscription_tier, created_at, updated_at, is_admin
`

type UpdateUserParams struct {
	ClerkID   string         `json:"clerk_id"`
	Email     string         `json:"email"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ClerkID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.SubscriptionTier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const updateUserSubscriptionTier = `-- name: UpdateUserSubscriptionTier :exec
UPDATE users SET subscription_tier = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserSubscriptionTierParams struct {
	ID               uuid.UUID `json:"id"`
	SubscriptionTier string    `json:"subscription_tier"`
}

func (q *Queries) UpdateUserSubscriptionTier(ctx context.Context, arg UpdateUserSubscriptionTierParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSubscriptionTier, arg.ID, arg.SubscriptionTier)
	return err
}
