// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: waitlist.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createWaitlistEntry = `-- name: CreateWaitlistEntry :one
INSERT INTO waitlist (email)
VALUES ($1)
RETURNING id, email, created_at
`

func (q *Queries) CreateWaitlistEntry(ctx context.Context, email string) (Waitlist, error) {
	row := q.db.QueryRowContext(ctx, createWaitlistEntry, email)
	var i Waitlist
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const deleteWaitlistEntry = `-- name: DeleteWaitlistEntry :exec
DELETE FROM waitlist WHERE id = $1
`

func (q *Queries) DeleteWaitlistEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWaitlistEntry, id)
	return err
}

const getWaitlistEntries = `-- name: GetWaitlistEntries :many
SELECT id, email, created_at FROM waitlist ORDER BY created_at DESC
`

func (q *Queries) GetWaitlistEntries(ctx context.Context) ([]Waitlist, error) {
	rows, err := q.db.QueryContext(ctx, getWaitlistEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Waitlist
	for rows.Next() {
		var i Waitlist
		if err := rows.Scan(&i.ID, &i.Email, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
