// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countUserActiveWebhooks = `-- name: CountUserActiveWebhooks :one
SELECT COUNT(*) FROM webhooks
WHERE user_id = $1 AND is_active = TRUE
`

func (q *Queries) CountUserActiveWebhooks(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserActiveWebhooks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (
    user_id,
    url,
    events,
    secret,
    is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, url, events, secret, is_active, created_at, updated_at
`

type CreateWebhookParams struct {
	UserID   uuid.UUID    `json:"user_id"`
	Url      string       `json:"url"`
	Events   []string     `json:"events"`
	Secret   string       `json:"secret"`
	IsActive sql.NullBool `json:"is_active"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, createWebhook,
		arg.UserID,
		arg.Url,
		pq.Array(arg.Events),
		arg.Secret,
		arg.IsActive,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		pq.Array(&i.Events),
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one

INSERT INTO webhook_deliveries (
    webhook_id,
    event_type,
    payload,
    status
) VALUES (
    $1, $2, $3, $4
) RETURNING id, webhook_id, event_type, payload, status, attempts, response_code, response_body, last_attempt_at, created_at
`

type CreateWebhookDeliveryParams struct {
	WebhookID uuid.UUID       `json:"webhook_id"`
	EventType string          `json:"event_type"`
	Payload   json.RawMessage `json:"payload"`
	Status    string          `json:"status"`
}

// Webhook Deliveries
func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, createWebhookDelivery,
		arg.WebhookID,
		arg.EventType,
		arg.Payload,
		arg.Status,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.LastAttemptAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks
WHERE id = $1 AND user_id = $2
`

type DeleteWebhookParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error {
	_, err := q.db.ExecContext(ctx, deleteWebhook, arg.ID, arg.UserID)
	return err
}

const getPendingWebhookDeliveries = `-- name: GetPendingWebhookDeliveries :many
SELECT id, webhook_id, event_type, payload, status, attempts, response_code, response_body, last_attempt_at, created_at FROM webhook_deliveries
WHERE status = 'pending' AND attempts < 3
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingWebhookDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.QueryContext(ctx, getPendingWebhookDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.ResponseCode,
			&i.ResponseBody,
			&i.LastAttemptAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, user_id, url, events, secret, is_active, created_at, updated_at FROM webhooks
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetWebhookByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWebhookByID(ctx context.Context, arg GetWebhookByIDParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhookByID, arg.ID, arg.UserID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		pq.Array(&i.Events),
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookDeliveryStats = `-- name: GetWebhookDeliveryStats :one
SELECT
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE status = 'success') as successful,
    COUNT(*) FILTER (WHERE status = 'failed') as failed,
    COUNT(*) FILTER (WHERE status = 'pending') as pending
FROM webhook_deliveries
WHERE webhook_id = $1
`

type GetWebhookDeliveryStatsRow struct {
	Total      int64 `json:"total"`
	Successful int64 `json:"successful"`
	Failed     int64 `json:"failed"`
	Pending    int64 `json:"pending"`
}

func (q *Queries) GetWebhookDeliveryStats(ctx context.Context, webhookID uuid.UUID) (GetWebhookDeliveryStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getWebhookDeliveryStats, webhookID)
	var i GetWebhookDeliveryStatsRow
	err := row.Scan(
		&i.Total,
		&i.Successful,
		&i.Failed,
		&i.Pending,
	)
	return i, err
}

const listActiveWebhooksByEvent = `-- name: ListActiveWebhooksByEvent :many
SELECT id, user_id, url, events, secret, is_active, created_at, updated_at FROM webhooks
WHERE is_active = TRUE AND $1 = ANY(events)
`

func (q *Queries) ListActiveWebhooksByEvent(ctx context.Context, events []string) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWebhooksByEvent, pq.Array(events))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			pq.Array(&i.Events),
			&i.Secret,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWebhooks = `-- name: ListUserWebhooks :many
SELECT id, user_id, url, events, secret, is_active, created_at, updated_at FROM webhooks
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserWebhooks(ctx context.Context, userID uuid.UUID) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listUserWebhooks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			pq.Array(&i.Events),
			&i.Secret,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, webhook_id, event_type, payload, status, attempts, response_code, response_body, last_attempt_at, created_at FROM webhook_deliveries
WHERE webhook_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookDeliveriesParams struct {
	WebhookID uuid.UUID `json:"webhook_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookDeliveries, arg.WebhookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.ResponseCode,
			&i.ResponseBody,
			&i.LastAttemptAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleWebhookStatus = `-- name: ToggleWebhookStatus :one
UPDATE webhooks
SET is_active = $2, updated_at = NOW()
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, url, events, secret, is_active, created_at, updated_at
`

type ToggleWebhookStatusParams struct {
	ID       uuid.UUID    `json:"id"`
	IsActive sql.NullBool `json:"is_active"`
	UserID   uuid.UUID    `json:"user_id"`
}

func (q *Queries) ToggleWebhookStatus(ctx context.Context, arg ToggleWebhookStatusParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, toggleWebhookStatus, arg.ID, arg.IsActive, arg.UserID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		pq.Array(&i.Events),
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks
SET url = $2, events = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $4
RETURNING id, user_id, url, events, secret, is_active, created_at, updated_at
`

type UpdateWebhookParams struct {
	ID     uuid.UUID `json:"id"`
	Url    string    `json:"url"`
	Events []string  `json:"events"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, updateWebhook,
		arg.ID,
		arg.Url,
		pq.Array(arg.Events),
		arg.UserID,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		pq.Array(&i.Events),
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookDelivery = `-- name: UpdateWebhookDelivery :exec
UPDATE webhook_deliveries
SET status = $2, attempts = $3, response_code = $4, response_body = $5, last_attempt_at = NOW()
WHERE id = $1
`

type UpdateWebhookDeliveryParams struct {
	ID           uuid.UUID      `json:"id"`
	Status       string         `json:"status"`
	Attempts     sql.NullInt32  `json:"attempts"`
	ResponseCode sql.NullInt32  `json:"response_code"`
	ResponseBody sql.NullString `json:"response_body"`
}

func (q *Queries) UpdateWebhookDelivery(ctx context.Context, arg UpdateWebhookDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhookDelivery,
		arg.ID,
		arg.Status,
		arg.Attempts,
		arg.ResponseCode,
		arg.ResponseBody,
	)
	return err
}
